spring:
  datasource:
    url: jdbc:mysql://www.hiyzx.cn:3307/activiti?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: yzx362311
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false
    asyncExecutorActivate: false
server:
  port: 8080
